import './globals.css'
import { Inter } from 'next/font/google'
import Provider from './provider'
import {Header, Footer} from './components/index'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className="dark:bg-nft-dark bg-white min-h-screen">
            <Header/>
            <div className="pt-65">
              {children}
            </div>
            <Footer/>
          </div>
          <Script src="https://kit.fontawesome.com/d57e6e2896.js" crossorigin="anonymous"></Script>
        </Provider>
      </body>
    </html>
  )
}
